import json

Chips = {
    "NOP":[
        [
            "IP_inc"
        ]
    ],
    "MOV_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "REG_write"
        ],
        [
            "IP_inc"
        ],
        [
            "IP_inc"
        ]
    ],
    "MOV_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-REG_ID",
            "MDR2_read",
            "MDR2-REG_IN",
            "REG_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "MOV_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "MOV_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MDR2-MEM_IN",
            "MEM_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "MOV_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MDR2_read",
            "MDR2-MEM_IN",
            "MEM_write"
        ]
    ],
    "MOV_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MEM_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "ADD_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "ADD_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "ADD_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MAR-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "ADD_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "ADD_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_write",
            "MEM_write"
        ]
    ],
    "ADD_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "SUB_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "SUB_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "SUB_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MAR-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "SUB_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "SUB_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_write",
            "MEM_write"
        ]
    ],
    "SUB_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "MUL_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "MUL_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "MUL_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MAR-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "MUL_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "MUL_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_write",
            "MEM_write"
        ]
    ],
    "MUL_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "DIV_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_RMAINDR-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "REG_write"
        ]
    ],
    "DIV_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "ALU_read",
            "ALU_RMAINDR-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "REG_write"
        ]
    ],
    "DIV_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MAR-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "ALU_read",
            "ALU_RMAINDR-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "REG_write"
        ]
    ],
    "DIV_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "DIV_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_write",
            "MEM_write"
        ]
    ],
    "DIV_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "PUSH_IMM":[
        [
            "SP_inc",
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "SP_read",
            "MAR_write",
            "MAR_read",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MEM_write"
        ]
    ],
    "PUSH_REG":[
        [
            "SP_inc",
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MEM_IN",
            "SP_read",
            "MAR_write",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "PUSH_MEM":[
        [
            "SP_inc",
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "MDR2_read",
            "MDR2-MEM_IN",
            "SP_read",
            "MAR_write",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "POP_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "SP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "SP_dec",
            "MAR_read",
            "MDR1_zero",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MEM_write"
        ]
    ],
    "POP_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "SP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "SP_dec",
            "MAR_read",
            "MEM_write"
        ],
        [
            "MDR2_read",
            "MDR2-MEM_IN",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "SHL_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 4",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "MDR1_read",
            "MDR1-REG_IN",
            "REG_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "SHL_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 4",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "SHR_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 5",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "MDR1_read",
            "MDR1-REG_IN",
            "REG_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "SHR_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 5",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "AND_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "AND_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "AND_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "AND_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "AND_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "AND_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "OR_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "OR_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "OR_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "OR_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "OR_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "OR_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "XOR_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "XOR_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "XOR_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "XOR_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "XOR_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "XOR_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "NOT_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "ALU_SELECT 7",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ]
    ],
    "NOT_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "ALU_SELECT 7",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MAR_read",
            "MEM_write"
        ]
    ],
    "CMP_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc"
        ],
        [
            "IP_inc"
        ]
    ],
    "CMP_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "CMP_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ]
    ],
    "CMP_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc"
        ]
    ],
    "CMP_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ]
    ],
    "CMP_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MDR1",
            "MDR1_write",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR2_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ]
    ],
    "XCHG_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MAR",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            "MDR0-REG_IN",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_write"
        ],
        [
            "MAR_read",
            "MAR-REG_ID",
            "MDR2_read",
            "MDR2-REG_IN",
            "REG_write"
        ]
    ],
    "XCHG_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_IN",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_write"
        ],
        [
            "MAR_read",
            "MDR2_read",
            "MDR2-MEM_IN",
            "MEM_write"
        ]
    ],
    "XCHG_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MAR-MDR1",
            "MDR1_write"
        ],
        [
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MAR_read",
            "MDR2_read",
            "MDR2-MEM_IN",
            "MEM_write"
        ],
        [
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MEM_write"
        ]
    ],
    
	"JMP_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            "IP_write"
        ]
    ],
    "JMP_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            "IP_write"
        ]
    ],
    "JZ_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"ZF-IP_write"
        ]
    ],
    "JZ_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"ZF-IP_write"
        ]
    ],
    "JNZ_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"!ZF-IP_write"
        ]
    ],
    "JNZ_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"!ZF-IP_write"
        ]
    ],
    "JS_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"SF-IP_write"
        ]
    ],
    "JS_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"SF-IP_write"
        ]
    ],
    "JNS_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"!SF-IP_write"
        ]
    ],
    "JNS_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"!SF-IP_write"
        ]
    ],
    "JG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"!ZF && !(SF^OF)-IP_write"
        ]
    ],
    "JG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"!ZF && !(SF^OF)-IP_write"
        ]
    ],
    "JGE_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"!(SF^OF)-IP_write"
        ]
    ],
    "JGE_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"!(SF^OF)-IP_write"
        ]
    ],
    "JL_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"SF^OF-IP_write"
        ]
    ],
    "JL_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"SF^OF-IP_write"
        ]
    ],
    "JLE_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"ZF && !(SF^OF)-IP_write"
        ]
    ],
    "JLE_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"ZF && !(SF^OF)-IP_write"
        ]
    ],
    "JA_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"!CF && !ZF-IP_write"
        ]
    ],
    "JA_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"!CF && !ZF-IP_write"
        ]
    ],
    "JAE_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"!CF-IP_write"
        ]
    ],
    "JAE_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"!CF-IP_write"
        ]
    ],
    "JB_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"CF-IP_write"
        ]
    ],
    "JB_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"CF-IP_write"
        ]
    ],
    "JBE_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"CF||ZF-IP_write"
        ]
    ],
    "JBE_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"CF||ZF-IP_write"
        ]
    ],
    "JP_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"PF-IP_write"
        ]
    ],
    "JP_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"PF-IP_write"
        ]
    ],
    "JNP_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"!PF-IP_write"
        ]
    ],
    "JNP_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"!PF-IP_write"
        ]
    ],
    "JO_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"OF-IP_write"
        ]
    ],
    "JO_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"OF-IP_write"
        ]
    ],
    "JNO_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            #"!OF-IP_write"
        ]
    ],
    "JNO_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "MDR1_read",
            #"!OF-IP_write"
        ]
    ]
}

for Instruction in Chips:
	j = {}
	with open(f"D:/DigitalLogicSim/python/8-Bit-CPU/GenChips/{Instruction}.json", "r", encoding="utf-8") as file:
		j = json.loads(file.read())
	j["Size"]["y"] = 5.0
	with open(f"D:/DigitalLogicSim/python/8-Bit-CPU/ResizedChips/{Instruction}.json", "w", encoding="utf-8") as file:
		file.write(json.dumps(j).encode().decode('unicode-escape'))