data: dict[str, list[list[str]]] = {
    "NOP":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MOV_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "REG_write"
        ],
        [
            "IP_inc"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MOV_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "MDR2_read",
            "MDR2-REG_IN",
            "REG_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MOV_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_IN",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MOV_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MDR1_read",
            "MDR1-MEM_IN",
            "MEM_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MOV_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MAR_read",
            "MDR2_read",
            "MDR2-MEM_IN",
            "MEM_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MOV_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write",
            "MAR_read",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "ADD_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "ADD_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "ADD_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_read",
            "REG_OUT-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MAR-ALU_IN0",
            "MDR0_read",
            "MDR0-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_IN",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "ADD_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "ADD_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "ADD_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1_write",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR0_read",
            "MDR0-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "SUB_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "SUB_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "SUB_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_read",
            "REG_OUT-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MAR-ALU_IN0",
            "MDR0_read",
            "MDR0-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "SUB_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "SUB_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "SUB_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1_write",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MUL_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MUL_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MUL_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_read",
            "REG_OUT-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MAR-ALU_IN0",
            "MDR0_read",
            "MDR0-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MUL_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MUL_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "MUL_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1_write",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 2",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "DIV_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 3",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_RMAINDR-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "DIV_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 3",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "ALU_read",
            "ALU_RMAINDR-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "DIV_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_read",
            "REG_OUT-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MAR-ALU_IN0",
            "MDR0_read",
            "MDR0-ALU_IN1",
            "ALU_SELECT 3",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_write"
        ],
        [
            "ALU_read",
            "ALU_RMAINDR-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_IN",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "DIV_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 3",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "DIV_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 3",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "DIV_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1_write",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 3",
            "ALU_write",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "MDR2_read",
            "MDR2-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "PUSH_IMM":[
        [
            "SP_dec",
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MEM_IN",
            "SP_read",
            "MAR_write",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "PUSH_REG":[
        [
            "SP_dec",
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MEM_IN",
            "SP_read",
            "MAR_write",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "PUSH_MEM":[
        [
            "SP_dec",
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1-write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MDR0_read",
            "MDR0-MEM_IN",
            "SP_read",
            "MAR_write",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "POP_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "SP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_IN",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_write"
        ],
        [
            "SP_inc",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "POP_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "SP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "SP_dec",
            "MAR_read",
            "MEM_write"
        ],
        [
            "MDR0_read",
            "MDR0-MEM_IN",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "SHL_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 4",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "SHL_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 4",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "SHR_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 5",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "SHR_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 5",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "AND_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "AND_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "AND_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2-write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR0_read",
            "MDR0-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "AND_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "AND_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "AND_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1_write",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 6",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "OR_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "OR_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "OR_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2-write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR0_read",
            "MDR0-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "OR_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "OR_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "OR_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1_write",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 8",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "XOR_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "XOR_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "XOR_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2-write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR0_read",
            "MDR0-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "XOR_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "XOR_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "XOR_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1_write",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR0",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "NOT_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "ALU_SELECT 7",
            "ALU_write"
        ],
        [
            "IP_inc",
            "ALU_read",
            "ALU_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-REG_IN",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "NOT_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "ALU_SELECT 7",
            "ALU_write"
        ],
        [
            "ALU_read",
            "ALU_OUT-MDR1",
            "MDR0_write",
            "MDR0_read",
            "MAR_read",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "CMP_REG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write",
            "MDR2_read",
            "MDR2-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "CMP_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "CMP_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "CMP_MEM_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 1",
            "ALU_write"
        ],
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "CMP_MEM_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR2_read",
            "MDR2-ALU_IN1",
            "ALU_SELECT 0",
            "ALU_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "CMP_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MDR1",
            "MDR1_write",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-ALU_IN0",
            "MDR1_read",
            "MDR1-ALU_IN1",
            "ALU_SELECT 9",
            "ALU_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "XCHG_REG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MAR",
            "MAR_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-REG_ID",
            "MDR2_read",
            "MDR2-REG_IN",
            "REG_write"
        ],
        [
            "MDR0_read",
            "MDR0-REG_ID",
            "MAR_read",
            "MAR-MDR1",
            "MDR1_write",
            "MDR1_read",
            "MDR1-REG_IN",
            "REG_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "XCHG_REG_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR0_read",
            "MDR0-MAR",
            "MAR_write",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_read",
            "REG_OUT-MDR2",
            "MDR2_write"
        ],
        [
            "IP_inc",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_IN",
            "MDR1_read",
            "MDR1-REG_ID",
            "REG_write"
        ],
        [
            "MAR_read",
            "MDR2_read",
            "MDR2-MEM_IN",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "XCHG_MEM_MEM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write",
            "MEM_read2",
            "MDR1_write"
        ],
        [
            "IP_inc",
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "IP_inc",
            "MDR2_read",
            "MDR2-MAR",
            "MAR_write"
        ],
        [
            "MDR0_read",
            "MDR0-MDR2",
            "MDR2_write"
        ],
        [
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "MAR_read",
            "MDR2_read",
            "MDR2-MEM_IN",
            "MEM_write"
        ],
        [
            "MDR1_read",
            "MDR1-MAR",
            "MAR_write",
            "MAR_read",
            "MDR0_read",
            "MDR0-MEM_IN",
            "MEM_write"
        ],
        [
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JMP_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "IP_write",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JMP_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "IP_write",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JZ_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "ZF-IP_write",
            "!ZF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JZ_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "ZF-IP_write",
            "!ZF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JNZ_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "!ZF-IP_write",
            "ZF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JNZ_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "!ZF-IP_write",
            "ZF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JS_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "SF-IP_write",
            "!SF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JS_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "SF-IP_write",
            "!SF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JNS_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "!SF-IP_write",
            "SF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JNS_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "!SF-IP_write",
            "SF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JG_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "!ZF &amp;&amp; !(SF^OF)-IP_write",
            "ZF || (SF^OF)-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JG_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "!ZF &amp;&amp; !(SF^OF)-IP_write",
            "ZF || (SF^OF)-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JGE_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "!(SF^OF)-IP_write",
            "SF^OF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JGE_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "!(SF^OF)-IP_write",
            "SF^OF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JL_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "SF^OF-IP_write",
            "!(SF^OF)-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JL_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "SF^OF-IP_write",
            "!(SF^OF)-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JLE_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "ZF &amp;&amp; !(SF^OF)-IP_write",
            "!ZF || (SF^OF)-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JLE_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "ZF &amp;&amp; !(SF^OF)-IP_write",
            "!ZF || (SF^OF)-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JA_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "!CF &amp;&amp; !ZF-IP_write",
            "CF || ZF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JA_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "!CF &amp;&amp; !ZF-IP_write",
            "CF || ZF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JAE_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "!CF-IP_write",
            "CF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JAE_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "!CF-IP_write",
            "CF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JB_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "CF-IP_write",
            "!CF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JB_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "CF-IP_write",
            "!CF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JBE_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "CF||ZF-IP_write",
            "!(CF||ZF)-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JBE_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "CF||ZF-IP_write",
            "!(CF||ZF)-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JP_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "PF-IP_write",
            "!PF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JP_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "PF-IP_write",
            "!PF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JNP_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "!PF-IP_write",
            "PF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JNP_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "!PF-IP_write",
            "PF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JO_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "OF-IP_write",
            "!OF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JO_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "OF-IP_write",
            "!OF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JNO_IMM":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write"
        ],
        [
            "ALU_readFlags",
            "MDR0_read",
            "!OF-IP_write",
            "OF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ],
    "JNO_REG":[
        [
            "IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "MDR0_write",
            "MDR0_read",
            "MDR0-REG_ID",
            "REG_read",
            "REG_OUT-MDR1",
            "MDR1_write"
        ],
        [
            "ALU_readFlags",
            "MDR1_read",
            "!OF-IP_write",
            "OF-IP_inc",
            "IP_read",
            "MAR_write",
            "MAR_read",
            "MEM_read",
            "CU_endInstruction"
        ]
    ]
}

microinstructions: list[str] = [
	"IP_inc",
	"IP_read",
	"IP_write",
	"SP_inc",
	"SP_dec",
	"SP_read",
	"SP_write",
	"MAR_read",
	"MAR_write",
	"MDR0_read",
	"MDR0_write",
	"MDR0_zero",
	"MDR1_read",
	"MDR1_write",
	"MDR1_zero",
	"MDR2_read",
	"MDR2_write",
	"MDR2_zero",
	"MEM_read",
	"MEM_read2",
	"MEM_write",
	"MDR0-MEM_IN",
	"MDR1-MEM_IN",
	"MDR2-MEM_IN",
	"MDR0-REG_IN",
	"MDR1-REG_IN",
	"MDR2-REG_IN",
	"MAR-REG_ID",
	"MDR0-REG_ID",
	"MDR1-REG_ID",
	"MDR2-REG_ID",
	"REG_OUT-MAR",
	"REG_OUT-MDR0",
	"REG_OUT-MDR1",
	"REG_OUT-MDR2",
	"REG_read",
	"REG_write",
	"MAR-MDR0",
	"MAR-MDR1",
	"MAR-MDR2",
	"MDR0-MAR",
	"MDR0-MDR1",
	"MDR0-MDR2",
	"MDR1-MAR",
	"MDR1-MDR0",
	"MDR1-MDR2",
	"MDR2-MAR",
	"MDR2-MDR0",
	"MDR2-MDR1",
	"MAR-ALU_IN0",
	"MDR0-ALU_IN0",
	"MDR1-ALU_IN0",
	"MDR2-ALU_IN0",
	"MAR-ALU_IN1",
	"MDR0-ALU_IN1",
	"MDR1-ALU_IN1",
	"MDR2-ALU_IN1",
	"ALU_SELECT 0",
	"ALU_SELECT 1",
	"ALU_SELECT 2",
	"ALU_SELECT 3",
	"ALU_SELECT 4",
	"ALU_SELECT 5",
	"ALU_SELECT 6",
	"ALU_SELECT 7",
	"ALU_SELECT 8",
	"ALU_SELECT 9",
	"ALU_SELECT 10",
	"ALU_SELECT 11",
	"ALU_read",
	"ALU_write",
	"ALU_readFlags",
	"ALU_OUT-MAR",
	"ALU_OUT-MDR0",
	"ALU_OUT-MDR1",
	"ALU_OUT-MDR2",
	"ALU_RMAINDR-MAR",
	"ALU_RMAINDR-MDR0",
	"ALU_RMAINDR-MDR1",
	"ALU_RMAINDR-MDR2",
	"CU_endInstruction"
]

# 70 microinstructions, one of which(ALU_SELECT) is 8 bits, so add 7
microinstructionBits = 77

def intToHex(num: int, length: int) -> str:
	"""intToHex(13, 3) == \"00d\""""
	return format(num, f"#0{length+2}x")[2:]
def splitByBin(num: int, bit: int) -> tuple[int, int]:
	binStr: str = format(num, f"#0{microinstructionBits + 2}b")
	a = len(binStr) # test: should be equal to the amount of microinstructionBits + 2
	cutStr: str = binStr[-bit:]
	cutStr2: str = binStr[2:-bit]
	b = len(cutStr) # test: should be equal to length
	bitNum: int = int(cutStr, 2)
	bitNum2: int = int(cutStr2, 2)
	return (bitNum, bitNum2)


microinstructionIDs: dict[str, int] = {}
k = 0
j = 0
AluSelect = False
# Populate microinstructionIDs
for microinstruction in microinstructions:
	if (not microinstruction.startswith("ALU_SELECT")):
		if (AluSelect):
			k += 8
			AluSelect = False

		microinstructionIDs[microinstruction] = 1 << k
		k += 1
	else:
		string = microinstruction[-2:]
		microinstructionIDs[microinstruction] = int(string) << k

		if (not AluSelect):
			AluSelect = True


maxCycles: int = 0
outData: list[list[int]] = [[0] * len(data)]

for index,name in enumerate(data):
	instruc = data[name]
	length = len(instruc)
	if (length > maxCycles):
		for cycle in range(maxCycles, length):
			with open(f"D:/Logisim/8-Bit-CPU/INS_ROM_{cycle}", "w", encoding="utf-8") as file:
				file.write("v3.0 hex words addressed\n00:")

			with open(f"D:/Logisim/8-Bit-CPU/INS_ROM2_{cycle}", "w", encoding="utf-8") as file:
				file.write("v3.0 hex words addressed\n00:")

			outData.append([0] * len(data))

		maxCycles = length



instrucInt: int = 0
for i, j in enumerate(data):
	for intCycle in range(len(data[j])):
		cycleID: int = 0
		cycle = data[j][intCycle] # if I add a type here, it throws an error when i try to redefine cycle as an int instead of a list[str] at the end of the script
		for microinstruction in cycle:
			try:
				cycleID += microinstructionIDs[microinstruction]
			except:
				if j.startswith("J") and microinstruction.endswith("IP_write"):
					continue
		
		outData[intCycle][instrucInt] = cycleID
	instrucInt += 1


for intCycle in range(maxCycles):
	cycle = outData[intCycle]
	k = 0
	for instruc in cycle:
		split: tuple[int, int] = splitByBin(instruc, 64)
		with open(f"D:/Logisim/8-Bit-CPU/INS_ROM_{intCycle}", "a", encoding="utf-8") as file:
			file.write(" " + intToHex(split[0], 16))
			
		with open(f"D:/Logisim/8-Bit-CPU/INS_ROM2_{intCycle}", "a", encoding="utf-8") as file:
			file.write(" " + intToHex(split[1], 4))
		
		k += 1